FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt update
RUN apt upgrade -y

# # Python install
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3.8 -y
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1
