FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt update
RUN apt upgrade -y

# Java install
RUN apt install wget unzip zip curl -y

# Java
RUN apt install openjdk-8-jdk -y

# Kotlin
RUN curl -s https://get.sdkman.io | bash
RUN /bin/bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kotlin" 

# Gradle
RUN wget -c https://services.gradle.org/distributions/gradle-8.1-bin.zip -P /tmp
RUN mkdir /opt/gradle
RUN unzip -d /opt/gradle /tmp/gradle-8.1-bin.zip
ENV PATH $PATH:/opt/gradle/gradle-8.1/bin

COPY demo demo
WORKDIR demo

CMD ["gradle", "run"]
